### PR TITLE
Cron ets flush

### LINKED ISSUE #49: [BUG] Memory leak via the ETS tables
**Describe the bug**
When defining a few metrics and starting my Elixir application, the ETS table growth constantly until there is no more RAM on the server.

**To Reproduce**

I use PromEx with default application and beam dashboards and one custom dashboards. 
I define these metrics in prom_ex:

```

counter("my_app.msg.in.count",
        description: "The total number of incoming msgs.",
        event_name: [:my_app, :msg, :in]
        ),
counter("my_app.msg.out.count",
        description: "The total number of outgoing msgs.",
        event_name: [:my_app, :msg, :out]
        )
```
One a second this event is fired:

```
%Msg{serial: serial, timestamp: timestamp} = msg
meta = %{serial: serial}
latency = System.os_time(:microsecond) - timestamp
measurement = %{latency: latency}
:telemetry.execute([:my_app, :msg, :in], measurement, meta)
```

and one second this one
```
%Msg{serial: serial, timestamp: timestamp} = msg
meta = %{serial: serial}
latency = System.os_time(:microsecond) - timestamp
measurement = %{latency: latency}
:telemetry.execute([:my_app, :msg, :out], measurement, meta)
```

I make a release and start it on a server. It goes out of memory after a while.

**Expected behavior**
Memory does not grow so fast and not so much to take multiple giga.

**Environment**

- Elixir version: Elixir 1.11.3 (compiled with Erlang/OTP 22)
- Erlang/OTP version: Erlang/OTP 22 [erts-10.7.2.7] [source] [64-bit] [smp:2:2] [ds:2:2:10] [async-threads:1] [hipe]
- Grafana version: Grafana v7.5.4 (615c153b3a)
- Prometheus version: 2.26.0

**Additional context**

Start of the app observerd with `observer_cli`:

observer1

A few minutes later, already much more memory:

observer2

We can see the ETS table takes the memory space. Observability.Metrics is where the PromEx stuff are defined:

obs3

This is memory graph from the application a day before this bug report:
checkmk(1)

The first slope on the left is linked to the first test deployment of the application with the metrics. Originally I had also `distribution` metrics in my code but the memory leak is triggered also without.

### PR DESCRIPTION
**Pull request by akoutmos**
Fixes #49

### CODE REVIEW

File: lib/prom_ex/ets_cron_flusher.ex [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  def handle_cast(:defer_ets_flush, state) do
+    # Cancel the existing timer
+    Process.cancel_timer(state.timer_ref)
+
+    timer_ref = schedule_flush()
+    {:noreply, %{state | timer_ref: timer_ref}}
+  end
+
+  defp schedule_flush do
+    Process.send_after(self(), :flush_ets, 7_500)
```
Comment (pallix) [inline lib/prom_ex/ets_cron_flusher.ex:66]: The default prometheus scrape interval mentioned [here](https://prometheus.io/docs/prometheus/latest/configuration/configuration/) is one minute so it could be more efficient to have a flushing interval higher than that. On the other hand, one minute is long and an application generating a lot of metrics could accumulate a lot in this timing interval.

Comment (akoutmos) [reply lib/prom_ex/ets_cron_flusher.ex:66]: Most deployments that I see are usually scraping every 5 or every 10 seconds....so I picked something in the middle. And for the reason you mentioned I didn't want to wait the whole minute to accumulate metrics.

Comment (pallix) [reply lib/prom_ex/ets_cron_flusher.ex:66]: Just to be sure I understand correctly: with a scraping every 10 seconds, the ets will be flushed at least once between two scrapes right?

Comment (akoutmos) [reply lib/prom_ex/ets_cron_flusher.ex:66]: That's correct. It'll look something like so:
```
      |-------7.5s--------|----2.5s----|
Scrape 1            Cron Flush      Scrape 2
```

In addition, every time an actual scrape occurs from Prometheus, the existing GenServer timer is canceled and a new one is created via the `handle_cast`. Another option would be to add a configuration value so that you can tweak this behavior, but I am hesitant to keep adding more config values.

**Comment by pallix** [comment]
Thanks :partying_face: ! It looks good, I have run the code for the last hours and could not identify any memory leak even if the was not dashboards (= no scraping).

**Comment by akoutmos** [comment]
Excellent news! I'll merge this in later today in that case and cut a release :)
